### ISSUE TITLE
Error cannot find parameter

### ISSUE THREAD

**Issue by ilCoso** [michaelkmartin/laravel-magento-integration#4]
Hi!

I'm trying to use your lib with laravel 4.2 but everytime I use a method like

``` php
var_dump( Magento::getMagentoVersion(optional $connection) );
```

I get a JSON like:

``` json
{
  "code": 500,
  "message": "Error cannot find parameter"
}
```

The stack trace is:

```
[2016-01-22 12:12:35] production.ERROR: exception 'Tinyrocket\Magento\Connections\MagentoSoapClientException' with message 'Error cannot find parameter' in /var/www/html/api.gamelife.it/vendor/tinyrocket/magento/src/Tinyrocket/Magento/Connections/MagentoSoapClient.php:112
Stack trace:
#0 /var/www/html/api.gamelife.it/vendor/tinyrocket/magento/src/Tinyrocket/Magento/Connections/MagentoSoapClient.php(82): Tinyrocket\Magento\Connections\MagentoSoapClient->__call('login', Array)
#1 /var/www/html/api.gamelife.it/vendor/tinyrocket/magento/src/Tinyrocket/Magento/Connections/MagentoSoapClient.php(82): Tinyrocket\Magento\Connections\MagentoSoapClient->login('cidiverte', 'gamelife')
#2 /var/www/html/api.gamelife.it/vendor/tinyrocket/magento/src/Tinyrocket/Magento/Magento.php(232): Tinyrocket\Magento\Connections\MagentoSoapClient->__construct(Array)
#3 /var/www/html/api.gamelife.it/bootstrap/compiled.php(3265): Tinyrocket\Magento\Magento->getMagentoVersion()
#4 /var/www/html/api.gamelife.it/app/controllers/MagentoController.php(14): Illuminate\Support\Facades\Facade::__callStatic('getMagentoVersi...', Array)
#5 /var/www/html/api.gamelife.it/app/controllers/MagentoController.php(14): Tinyrocket\Magento\Facades\Magento::getMagentoVersion()
#6 [internal function]: MagentoController->index()
#7 /var/www/html/api.gamelife.it/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#8 /var/www/html/api.gamelife.it/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('index', Array)
#9 /var/www/html/api.gamelife.it/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(MagentoController), Object(Illuminate\Routing\Route), 'index')
#10 /var/www/html/api.gamelife.it/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'MagentoControll...', 'index')
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#12 /var/www/html/api.gamelife.it/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array)
#13 /var/www/html/api.gamelife.it/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#14 /var/www/html/api.gamelife.it/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#15 /var/www/html/api.gamelife.it/bootstrap/compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /var/www/html/api.gamelife.it/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /var/www/html/api.gamelife.it/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/html/api.gamelife.it/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#19 /var/www/html/api.gamelife.it/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/html/api.gamelife.it/bootstrap/compiled.php(11088): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#21 /var/www/html/api.gamelife.it/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#22 /var/www/html/api.gamelife.it/public/index.php(49): Illuminate\Foundation\Application->run()
#23 {main} [] []
```

I'm doing something wrong?

Thanks.

**Comment by Sejido** [comment]
i think tinyrocket doesn't work with laravel 4.2

**Comment by iveoles** [comment]
I'm using it on 4.2. Is that code verbatim above? You should be calling 

    var_dump( Magento::getMagentoVersion() );
